### ISSUE TITLE
Driver "opennebula" not found even though "docker-machine-driver-opennebula" is accessible in the PATH.

### ISSUE THREAD

**Issue by teterkin** [OpenNebula/docker-machine-opennebula#10]
Hello,
I get **"Driver opennebula not found"** error:
`
[teterkin@teterkin-nb3 ~]$ docker-machine create --driver opennebula --opennebula-network-name cloud --opennebula-image-id 1 --opennebula-b2d-size 100 b2d
Driver "opennebula" not found. Do you have the plugin binary "docker-machine-driver-opennebula" accessible in your PATH?
[teterkin@teterkin-nb3 ~]$
`

The "docker-machine-driver-opennebula" file is in place and executable:
`
[teterkin@teterkin-nb3 ~]$ ls -la ~/go/bin/docker-machine-driver-opennebula
-rwxr-xr-x 1 teterkin 1049089 10653696 ноя 17 18:45 /c/Users/teterkin/go/bin/docker-machine-driver-opennebula*
[teterkin@teterkin-nb3 ~]$
`

PATH includes "/c/Users/teterkin/go/bin/" path:
`
[teterkin@teterkin-nb3 ~]$ echo $PATH | grep -c "/c/Users/teterkin/go/bin"
1
[teterkin@teterkin-nb3 ~]$
`

If I just type "docker-machine-driver-opennebula" it runs ok:
`
[teterkin@teterkin-nb3 ~]$ docker-machine-driver-opennebula
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
(API version: 1)
[teterkin@teterkin-nb3 ~]$
`

I run this from Windows10 (1703, build 15063.726).
Git Bash shell 2.10.1.1.
I am running Docker CE version 17.09.0-ce-win33 (13620).
Docker-machine version is  0.13.0, build 9ba6da9. 

**What else can I check?**

**Comment by km4rcus** [comment]
Hi @teterkin,

Maybe it is an issue related to Windows. Could you check this (https://github.com/docker/machine/issues/3452) and see if it solves your problem?

**Comment by jmelis** [comment]
Hi @teterkin, did you have the chance to take a look at @km4rcus suggestion?

**Comment by jmelis** [comment]
Closing issue. Feel free to reopen if you can provide more information.
