### ISSUE TITLE
Driver errors

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/docker-machine-opennebula#3]
Hello, I have problems with this driver on our gitlab server. See result of `docker-machine ls` and `rm`

		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		Error attempting call to get driver name: connection is shut down
		NAME                                             ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER    ERRORS

		runner-9b0cd30b-auto-scale-1484827030-3a308374   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484827030-da7ee797   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484828199-0739e8bf   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484828202-4e05e7c6   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484829357-08cac59f   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484829375-227e5a78   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484830405-f2ab3325   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484830444-f6427a02   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484831515-a870fcdd   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484831569-fa41e245   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484832658-c3b7ada4   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484832730-132551ed   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484833570-95f21b2c   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484833669-3598beb6   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484834602-8d1ef474   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484834740-10b5ce6a   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484835641-df00c33d   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484835785-fb3bd1a9   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484836748-0632f50c   -                 Error                 Unknown   unexpected EOF
		runner-9b0cd30b-auto-scale-1484836859-e9dea166   -                 Error                 Unknown   unexpected EOF

		About to remove runner-9b0cd30b-auto-scale-1484827030-3a308374
		Are you sure? (y/n): y
		Error removing host "runner-9b0cd30b-auto-scale-1484827030-3a308374": unexpected EOF

**Comment by feldsam** [comment]
My .bashrc config:

		export ONE_XMLRPC=http://hostname:2633/RPC2
		export ONE_AUTH=~/.one/one_auth

docker-machine version 0.7.0, build a650a40

I also updated to 0.9.0 right now, but same errors. Machines stared in opennebula, but in docker-machine are in error state

**Comment by jirutka** [comment]
There’s a workaround for this error:

```patch
This patch fixes errors like:

  Error attempting call to get driver name: connection is shut down
  (runner-c2db3a9a-ict-1487649355-43f4611f) DBG | ... Post : unsupported protocol scheme ""
  unexpected EOF

More details:
`d.Config` is initially empty, `d.buildConfig()` must be called to load
the actual configuration. But it's called only in `Create()` method, so
in all other cases empty config is passed into goca and eventually into
goca's `Call()` method. There it goes into `xmlrpcClient` that returns
error `unsupported protocol scheme ""`. This error is not returned, but
instead logged using `log.Fatal`. And because Go is totally retarted,
this *logging* method calls `os.Exit(1)`... So the plugin process
prematurely dies and docker-machine, obviously, isn't very happy...

--- a/opennebula.go
+++ b/opennebula.go
@@ -103,6 +103,7 @@
 }

 func (d *Driver) setClient() error {
+	d.buildConfig()
 	return goca.SetClient(d.Config)
 }

@@ -365,7 +366,6 @@
 	}

 	// build config and set the xmlrpc client
-	d.buildConfig()
 	d.setClient()

 	// Create template
```

**Comment by jmelis** [comment]
Fixed
