### ISSUE TITLE
Multiple NICs

### ISSUE THREAD

**Issue by koekie** [OpenNebula/docker-machine-opennebula#8]
I wanted to attach multiple nics to a machine I am provisioning in a OpenNebula cloud. But this is not possible at the moment.
Is it a good idea to support such a thing? Or are there any issues or restrictions why you cannot attach multiple NICs to a machine provisioned by docker-machine?

**Comment by jmelis** [comment]
I've been looking at the offical drivers [1], and afaik they don't support multiple NICs. Closing this issue, but please reopen if you can find an example or official support to do that in the upstream project.

[1] https://docs.docker.com/machine/drivers/
