### ISSUE TITLE
swarm config might not be working

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/docker-machine-opennebula#9]
So I tried this, which ought to bring up a swarm master?!

```
utopia:~ floh$ docker-machine create --driver opennebula --opennebula-template-name boot2docker --swarm-master smas
Running pre-create checks...
Creating machine...
(smas) Creating SSH key...
(smas) Starting	 VM...
(smas) Waiting for SSH...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring swarm...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env smas
```

And I also brought up one node to join that swarm, but let's ignore that, it seems to not matter.

Let's look at the general connect instead - it seems to not be OK:

```
utopia:~ floh$ eval $(docker-machine env --swarm smas)
Error checking TLS connection: Connection to Swarm cannot be checked but the certs are valid. Maybe swarm is not started
```
The command was run a few minutes after the master was created.

I retried once more giving it 2GB ram, but no success.

docker daemon is ok:
```
utopia:~ floh$ eval $(docker-machine env smas)
utopia:~ floh$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.0-ce-rc3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.71-boot2docker
Operating System: Boot2Docker 17.06.0-ce-rc3 (TCL 7.2); master : 5d12baf - Tue Jun 13 21:56:36 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955GiB
Name: smas
ID: CKFJ:Z3G5:GPSD:FKB3:LUO2:WFXV:SIQV:5TJ7:LVID:V2A6:C6D2:W75F
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 28
 System Time: 2017-10-25T01:39:37.497170996Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=opennebula
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

So honestly I don't think this is a _me problem_.
If it is, please forgive me.

**Comment by FlorianHeigl** [comment]
Or it might be an issue with the boot2docker version 17.06 vs. my local OSX one.

```
utopia:~ floh$ docker-machine --help
Usage: docker-machine [OPTIONS] COMMAND [arg...]

Create and manage machines running Docker.

Version: 0.12.2, build 9371605
```

I am not sure if that is what's going on and don't think that's it since during install it _says it configured swarm_!

Something must be wrong if there's no error logged but the two versions are incompatible to death.

here's the thinggy:
```
utopia:~ floh$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS               NAMES
f2a8fac9919b        swarm:latest        "/swarm manage --t..."   About a minute ago   Restarting (1) 19 seconds ago                       swarm-agent-master
```

So seems this thing is just not working:

```
docker@smas:~$ docker start f2a8fac9919b
f2a8fac9919b
docker@smas:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                              NAMES
f2a8fac9919b        swarm:latest        "/swarm manage --t..."   3 minutes ago       Up Less than a second   2375/tcp, 0.0.0.0:3376->3376/tcp   swarm-agent-master
docker@smas:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
f2a8fac9919b        swarm:latest        "/swarm manage --t..."   3 minutes ago       Restarting (1) 1 second ago                       swarm-agent-master
docker@smas:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                                  PORTS               NAMES
f2a8fac9919b        swarm:latest        "/swarm manage --t..."   3 minutes ago       Restarting (1) Less than a second ago                       swarm-agent-master
```

Debug socket is not alive in this situation either:
```
docker@smas:~$ test -s /var/run/docker.socket ; echo $?
1
docker@smas:~$ curl  --unix-socket /var/run/docker.socket http://info
curl: (7) Couldn't connect to server
```

*I hope someone can make sense of this info - has anyone tested the swarm setup feature recently?*

I think swarm config is of the most important parts when trying this - and needs to work with boot2docker template from the marketplace since that is the most available choice to set it up.

(Personally, I hate this mess. Just trying to be thorough to make sure the basics either work or throw proper errors... And *grin* document it some more)

**Comment by FlorianHeigl** [comment]
Tried one more thing, I passed a --swarm-discovery token://blah (though I would quite much assume that if it starts without doing that i'll autogenerate. But that's just me...)

Now, 
On the client:
```
Swarm: inactive
```
On the master, at first: nope.
Then after 1-2 minutes:
```
utopia:~ floh$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: swarm/1.2.8
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 1
 smac1: 192.168.20.167:2376
  └ ID: N4DM:GKVS:2F46:S4VI:Q72M:ZYY5:R6FB:U7QE:6JPO:Q4TH:GJ37:C7CX|192.168.20.167:2376
  └ Status: Healthy
  └ Containers: 1 (1 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 780.7 MiB
  └ Labels: kernelversion=4.4.71-boot2docker, operatingsystem=Boot2Docker 17.06.0-ce-rc3 (TCL 7.2); master : 5d12baf - Tue Jun 13 21:56:36 UTC 2017, ostype=linux, provider=opennebula, storagedriver=aufs
```

So it took around 2 minutes and then the stupid thing joined.
I'm not sure, but seems it's just a stupidity in docker-machine that it's starting the vm when not given a token but needing it. Plus some slowness in joining up.

Added another node and it seems to just take some time.

Please comment if you got anything to add, and I'll later create a PR to the README.md that should save the next person this hassle.

**Comment by km4rcus** [comment]
Hi @FlorianHeigl ,

for building a swarm cluster you can follow two approaches, one based on swarmkit and another on swarm standalone.

For swarmkit, integrated in docker, you can follow this [guide](https://docs.docker.com/get-started/part4/#create-a-cluster).

For swarm standalone with docker-machine, you can follow the [blog post]( https://opennebula.org/docker-swarm-with-opennebula). I just tested it and it works.

**Comment by FlorianHeigl** [comment]
Hey!

1) what's the reason that you generally use --opennebula-image-name boot2docker --opennebula-b2d-size 10240 instead of the template that comes with it?
I noticed much of the tooling works better that way, but don't understand the story behind it.

2) I'll go over the readme and make sure that both these guides are pointed at where one can see it. :-)
